nekostreamer/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin


urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^play/", include('play.urls', namespace="play")),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

play/urls.py
from django.conf.urls import  url
from .views import entry_list, entry_add

urlpatterns = [
    url(r"add$", entry_add, name="add"),
    url(r"$", entry_list, name="list"),
]

play/models.py
from __future__ import unicode_literals

from django.db import models
from account.models import Account


class Entry(models.Model):
    account = models.ForeignKey(Account)
    url = models.URLField()

    def __unicode__(self):
        return self.url

play/views.py
from django.views.generic import ListView, CreateView
from .models import Entry

class EntryList(ListView):
    model = Entry

entry_list = EntryList.as_view()

class EntryAdd(CreateView):
    model = Entry
    fields = ["url"]

entry_add = EntryAdd.as_view()

nekostreamer/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <p class="navbar-text">
            <i class="fa fa-user"></i> {% user_display request.user %}
        </p>
        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

nekostreamer/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2016 &lt;your company here&gt;" %}

nekostreamer/templates/_scripts.html
<script src='/site_media/static/js/site-5e73bbeeb0.js'></script>

nekostreamer/templates/_styles.html
<link href='/site_media/static/css/site-e7b87bbea0.css' rel='stylesheet' />

nekostreamer/templates/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <section class="jumbotron">
        <div class="container">
            {% include "_messages.html" %}
            <h1>{% blocktrans %}Welcome to<br>pinax-project-account{% endblocktrans %}</h1>
            <p>
                {% blocktrans %}
                In addition to what is provided by the "zero" project, this project
                provides thorough integration with django-user-accounts, adding
                comprehensive account management functionality. It is a foundation
                suitable for most sites that have user accounts.
                {% endblocktrans %}
            </p>
            {% if not user.is_authenticated %}
            {% url "account_login" as login_url %}
            {% url "account_signup" as signup_url %}
            <p>{% blocktrans %}You can <a href="{{ login_url }}" class="btn btn-default">Log In</a> or <a href="{{ signup_url }}" class="btn btn-primary">Sign Up</a> to try out the site.{% endblocktrans %}</p>
            {% endif %}
        </div>
    </section>
    <section>
        <div class="container">
            <h2 class="text-center">{% blocktrans %}What is Pinax?{% endblocktrans %}</h2>
            <p class="lead">
                {% blocktrans %}
                <b>Pinax</b> is an open-source platform based on Django and
                intended to provide a starting point for websites. It takes
                care of the things that many sites have in common, so you can
                focus on what makes your site different.
                {% endblocktrans %}
            </p>
            <div class="feature-columns">
                <div>
                    <i class="fa fa-cubes fa-3x"></i><br>
                    {% blocktrans %}
                    <b>Starter projects</b> provide project layout,
                    scaffolding, already integrated components and
                    ready-to-go code.
                    {% endblocktrans %}
                </div>
                <div>
                    <i class="fa fa-puzzle-piece fa-3x"></i><br>
                    {% blocktrans %}
                    <b>Reusable apps</b> provide common
                    infrastructure, back-end functionality,
                    and user-facing components.
                    {% endblocktrans %}
                </div>
                <div>
                    <i class="fa fa-tint fa-3x"></i><br>
                    {% blocktrans %}
                    <b>Themes</b> provide default templates and
                    stylesheets for quick prototyping and easy customization.
                    {% endblocktrans %}
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <p class="lead text-center">
                {% blocktrans %}
                See <a href="http://pinaxproject.com/">pinaxproject.com</a>
                for more information.
                {% endblocktrans %}
            </p>
        </div>
    </section>
{% endblock %}

nekostreamer/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load metron_tags %}
{% load i18n %}


{% block styles %}
    {% include "_styles.html" %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
{% endblock %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}

play/templates/play/entry_form.html
{% extends "site_base.html" %}

{% load i18n bootstrap_tags %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}

<section>
  <div class="container">

<form method="post">
    <legend>My Form</legend>
    {% csrf_token %}
    {{ form|as_bootstrap }}
    <div class="form-actions">
      <a href="{% url 'play:list' %}" class="btn">Go back</a>
      <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>

  </div>
</section>
{% endblock %}

play/templates/play/entry_list.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}pinax-project-account{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}

<section>
  <div class="container">



    <a href="{% url 'play:add'%}"> {% trans "add" %}</a>
    <table>
      <tr>
        <th>Urls</th>
      </tr>
      {% for object in objects %}
      <tr>
        <td>
          {{object.url}}  
        </td>
      </tr>

      {% endfor %}
    </table>

  </div>
</section>
{% endblock %}